### ISSUE TITLE
Weird conception

### ISSUE THREAD

**Issue by wasyleque** [Chia-Network/wallets#53]
As I understand if one of my plots is on challenge than a bigger farm is always winning ?
So there is no chance at all and no point to farm individually even with 16 - 64 TB. 
Will You change something to interest small farmers in farming and ploting without join bigger farm ?
There`s a huge monopoly at few places, so the small farmers have zero chances to win.

**Comment by wjblanke** [comment]
The network only cares about the quality of the proof. It has no knowledge wrt/the size of the farmer.
